const translations = {
  it: {
    title: "Strumento di Centratura",
    subtitle: "Analizza la centratura della tua carta Pokémon con precisione.",
    uploadInstruction: "Carica un'immagine ad alta risoluzione della tua carta.",
    dragGuides: "Trascina i quadratini colorati per posizionare le guide ai bordi.",
    resultTitle: "Risultati",
    globalCentering: "Centratura Globale",
    horizontal: "Orizzontale",
    vertical: "Verticale",
    mm: "mm",
    percent: "%",
    psa: "Voto PSA",
    bgs: "Voto BGS",
    sgc: "Voto SGC",
    instructionsTab: "📘 Istruzioni",
    toolTab: "🛠️ Strumento",
    languageLabel: "Lingua",
    uploadButton: "Carica Immagine",
    resetButton: "Reset",
    generatePdfButton: "Genera PDF",
    downloadButton: "Scarica PDF",
    leftInner: "Bordo sinistro interno",
    leftOuter: "Bordo sinistro esterno",
    rightInner: "Bordo destro interno",
    rightOuter: "Bordo destro esterno",
    topInner: "Bordo superiore interno",
    topOuter: "Bordo superiore esterno",
    bottomInner: "Bordo inferiore interno",
    bottomOuter: "Bordo inferiore esterno",
    disclaimerTitle: "⚠️ Disclaimer",
    disclaimerParagraphs: [
      "⚠️ Questa è un'applicazione amatoriale.",
      "🎓 È pensata per fornire un'idea preliminare della centratura di una carta.",
      "❌ I risultati e i voti ipotetici non sono ufficiali né garantiscono il voto reale.",
      "🧪 Usala come pre-analisi, ma affidati a una valutazione professionale per il grading."
    ]
  },
  en: {
    title: "Centering Tool",
    subtitle: "Analyze your Pokémon card centering with precision.",
    uploadInstruction: "Upload a high-resolution image of your card.",
    dragGuides: "Drag the colored squares to place border guides.",
    resultTitle: "Results",
    globalCentering: "Global Centering",
    horizontal: "Horizontal",
    vertical: "Vertical",
    mm: "mm",
    percent: "%",
    psa: "PSA Grade",
    bgs: "BGS Grade",
    sgc: "SGC Grade",
    instructionsTab: "📘 Instructions",
    toolTab: "🛠️ Tool",
    languageLabel: "Language",
    uploadButton: "Upload Image",
    resetButton: "Reset",
    generatePdfButton: "Generate PDF",
    downloadButton: "Download PDF",
    leftInner: "Left Inner Border",
    leftOuter: "Left Outer Border",
    rightInner: "Right Inner Border",
    rightOuter: "Right Outer Border",
    topInner: "Top Inner Border",
    topOuter: "Top Outer Border",
    bottomInner: "Bottom Inner Border",
    bottomOuter: "Bottom Outer Border",
    disclaimerTitle: "⚠️ Disclaimer",
    disclaimerParagraphs: [
      "⚠️ This is a non-official hobby application.",
      "🎓 It is intended to provide a preliminary idea of card centering.",
      "❌ Results and grades shown are not official and not guaranteed.",
      "🧪 Use it as a pre-analysis tool, but rely on professional grading for certification."
    ]
  },
  zh: {
    title: "居中工具",
    subtitle: "精准分析您的宝可梦卡片居中情况。",
    uploadInstruction: "上传您的卡片高分辨率图像。",
    dragGuides: "拖动彩色方块以放置边缘参考线。",
    resultTitle: "结果",
    globalCentering: "整体居中",
    horizontal: "水平",
    vertical: "垂直",
    mm: "毫米",
    percent: "%",
    psa: "PSA 评分",
    bgs: "BGS 评分",
    sgc: "SGC 评分",
    instructionsTab: "📘 使用说明",
    toolTab: "🛠️ 工具",
    languageLabel: "语言",
    uploadButton: "上传图片",
    resetButton: "重置",
    generatePdfButton: "生成 PDF",
    downloadButton: "下载 PDF",
    leftInner: "左内边",
    leftOuter: "左外边",
    rightInner: "右内边",
    rightOuter: "右外边",
    topInner: "上内边",
    topOuter: "上外边",
    bottomInner: "下内边",
    bottomOuter: "下外边",
    disclaimerTitle: "⚠️ 免责声明",
    disclaimerParagraphs: [
      "⚠️ 本应用为非官方的业余工具。",
      "🎓 仅用于初步评估卡片的居中情况。",
      "❌ 显示的结果和评分不具有官方效力，也无法保证。",
      "🧪 请作为预分析参考，正式评分应依赖专业机构。"
    ]
  },
  ja: {
    title: "センタリングツール",
    subtitle: "ポケモンカードのセンタリングを正確に分析します。",
    uploadInstruction: "カードの高解像度画像をアップロードしてください。",
    dragGuides: "色付きの四角をドラッグしてガイドを配置します。",
    resultTitle: "結果",
    globalCentering: "全体のセンタリング",
    horizontal: "水平",
    vertical: "垂直",
    mm: "mm",
    percent: "%",
    psa: "PSA評価",
    bgs: "BGS評価",
    sgc: "SGC評価",
    instructionsTab: "📘 使い方",
    toolTab: "🛠️ ツール",
    languageLabel: "言語",
    uploadButton: "画像をアップロード",
    resetButton: "リセット",
    generatePdfButton: "PDFを生成",
    downloadButton: "PDFをダウンロード",
    leftInner: "左内側の枠",
    leftOuter: "左外側の枠",
    rightInner: "右内側の枠",
    rightOuter: "右外側の枠",
    topInner: "上内側の枠",
    topOuter: "上外側の枠",
    bottomInner: "下内側の枠",
    bottomOuter: "下外側の枠",
    disclaimerTitle: "⚠️ 免責事項",
    disclaimerParagraphs: [
      "⚠️ このアプリは非公式の趣味ツールです。",
      "🎓 カードのセンタリングを事前に確認するためのものです。",
      "❌ 表示された結果や評価は公式なものではなく、保証されません。",
      "🧪 正式な評価には専門のグレーディングサービスを利用してください。"
    ]
  },
  ko: {
    title: "중심 정렬 도구",
    subtitle: "포켓몬 카드의 중심 정렬을 정밀하게 분석하세요.",
    uploadInstruction: "카드의 고해상도 이미지를 업로드하세요.",
    dragGuides: "색상 사각형을 드래그하여 테두리 가이드를 배치하세요.",
    resultTitle: "결과",
    globalCentering: "전체 중심 정렬",
    horizontal: "수평",
    vertical: "수직",
    mm: "mm",
    percent: "%",
    psa: "PSA 점수",
    bgs: "BGS 점수",
    sgc: "SGC 점수",
    instructionsTab: "📘 설명서",
    toolTab: "🛠️ 도구",
    languageLabel: "언어",
    uploadButton: "이미지 업로드",
    resetButton: "초기화",
    generatePdfButton: "PDF 생성",
    downloadButton: "PDF 다운로드",
    leftInner: "왼쪽 내부 테두리",
    leftOuter: "왼쪽 외부 테두리",
    rightInner: "오른쪽 내부 테두리",
    rightOuter: "오른쪽 외부 테두리",
    topInner: "상단 내부 테두리",
    topOuter: "상단 외부 테두리",
    bottomInner: "하단 내부 테두리",
    bottomOuter: "하단 외부 테두리",
    disclaimerTitle: "⚠️ 면책 조항",
    disclaimerParagraphs: [
      "⚠️ 이 앱은 비공식적인 취미용 도구입니다.",
      "🎓 카드 중심 정렬을 미리 파악하기 위한 용도로 제공됩니다.",
      "❌ 표시된 결과와 등급은 공식적인 것이 아니며 보장되지 않습니다.",
      "🧪 정식 평가를 위해서는 전문가의 그레이딩을 이용하세요."
    ]
  }
};

export default translations;
