const translations = {
  it: {
    title: "Strumento di Centratura",
    subtitle: "Analizza la centratura della tua carta Pokémon con precisione.",
    uploadInstruction: "Carica un'immagine ad alta risoluzione della tua carta.",
    dragGuides: "Trascina i quadratini colorati per posizionare le guide ai bordi.",
    resultTitle: "Risultati",
    globalCentering: "Centratura Globale",
    horizontal: "Orizzontale",
    vertical: "Verticale",
    mm: "mm",
    percent: "%",
    psa: "Voto PSA",
    bgs: "Voto BGS",
    sgc: "Voto SGC",
    instructionsTab: "📘 Istruzioni",
    toolTab: "🛠️ Strumento",
    languageLabel: "Lingua",
    uploadButton: "Carica Immagine",
    resetButton: "Reset",
    generatePdfButton: "Genera PDF",
    downloadButton: "Scarica PDF",
    leftInner: "Bordo sinistro interno",
    leftOuter: "Bordo sinistro esterno",
    rightInner: "Bordo destro interno",
    rightOuter: "Bordo destro esterno",
    topInner: "Bordo superiore interno",
    topOuter: "Bordo superiore esterno",
    bottomInner: "Bordo inferiore interno",
    bottomOuter: "Bordo inferiore esterno",
    disclaimerTitle: "⚠️ Disclaimer",
    disclaimerParagraphs: [
      "⚠️ Questa è un'applicazione amatoriale.",
      "🎓 È pensata per fornire un'idea preliminare della centratura di una carta.",
      "❌ I risultati e i voti ipotetici non sono ufficiali né garantiscono il voto reale.",
      "🧪 Usala come pre-analisi, ma affidati a una valutazione professionale per il grading."
    ]
  },
  en: {
    title: "Centering Tool",
    subtitle: "Analyze your Pokémon card centering with precision.",
    uploadInstruction: "Upload a high-resolution image of your card.",
    dragGuides: "Drag the colored squares to place border guides.",
    resultTitle: "Results",
    globalCentering: "Global Centering",
    horizontal: "Horizontal",
    vertical: "Vertical",
    mm: "mm",
    percent: "%",
    psa: "PSA Grade",
    bgs: "BGS Grade",
    sgc: "SGC Grade",
    instructionsTab: "📘 Instructions",
    toolTab: "🛠️ Tool",
    languageLabel: "Language",
    uploadButton: "Upload Image",
    resetButton: "Reset",
    generatePdfButton: "Generate PDF",
    downloadButton: "Download PDF",
    leftInner: "Left Inner Border",
    leftOuter: "Left Outer Border",
    rightInner: "Right Inner Border",
    rightOuter: "Right Outer Border",
    topInner: "Top Inner Border",
    topOuter: "Top Outer Border",
    bottomInner: "Bottom Inner Border",
    bottomOuter: "Bottom Outer Border",
    disclaimerTitle: "⚠️ Disclaimer",
    disclaimerParagraphs: [
      "⚠️ This is a non-official hobby application.",
      "🎓 It is intended to provide a preliminary idea of card centering.",
      "❌ Results and grades shown are not official and not guaranteed.",
      "🧪 Use it as a pre-analysis tool, but rely on professional grading for certification."
    ]
  },
  fr: {
    title: "Outil de Centrage",
    subtitle: "Analysez le centrage de votre carte Pokémon avec précision.",
    uploadInstruction: "Téléchargez une image haute résolution de votre carte.",
    dragGuides: "Faites glisser les carrés colorés pour placer les repères de bord.",
    resultTitle: "Résultats",
    globalCentering: "Centrage Global",
    horizontal: "Horizontal",
    vertical: "Vertical",
    mm: "mm",
    percent: "%",
    psa: "Note PSA",
    bgs: "Note BGS",
    sgc: "Note SGC",
    instructionsTab: "📘 Instructions",
    toolTab: "🛠️ Outil",
    languageLabel: "Langue",
    uploadButton: "Télécharger Image",
    resetButton: "Réinitialiser",
    generatePdfButton: "Générer le PDF",
    downloadButton: "Télécharger PDF",
    leftInner: "Bord intérieur gauche",
    leftOuter: "Bord extérieur gauche",
    rightInner: "Bord intérieur droit",
    rightOuter: "Bord extérieur droit",
    topInner: "Bord supérieur intérieur",
    topOuter: "Bord supérieur extérieur",
    bottomInner: "Bord inférieur intérieur",
    bottomOuter: "Bord inférieur extérieur",
    disclaimerTitle: "⚠️ Avertissement",
    disclaimerParagraphs: [
      "⚠️ Ceci est une application amateur.",
      "🎓 Elle est destinée à fournir une idée préliminaire du centrage d'une carte.",
      "❌ Les résultats et notes ne sont pas officiels ni garantis.",
      "🧪 Utilisez-la comme outil préliminaire, mais faites appel à un service de notation professionnel."
    ]
  },
  de: {
    title: "Zentrierungs-Tool",
    subtitle: "Analysieren Sie die Zentrierung Ihrer Pokémon-Karte präzise.",
    uploadInstruction: "Laden Sie ein hochauflösendes Bild Ihrer Karte hoch.",
    dragGuides: "Ziehen Sie die farbigen Quadrate, um Randführungen zu platzieren.",
    resultTitle: "Ergebnisse",
    globalCentering: "Globale Zentrierung",
    horizontal: "Horizontal",
    vertical: "Vertikal",
    mm: "mm",
    percent: "%",
    psa: "PSA Bewertung",
    bgs: "BGS Bewertung",
    sgc: "SGC Bewertung",
    instructionsTab: "📘 Anleitung",
    toolTab: "🛠️ Werkzeug",
    languageLabel: "Sprache",
    uploadButton: "Bild Hochladen",
    resetButton: "Zurücksetzen",
    generatePdfButton: "PDF generieren",
    downloadButton: "PDF Herunterladen",
    leftInner: "Linker Innenrand",
    leftOuter: "Linker Außenrand",
    rightInner: "Rechter Innenrand",
    rightOuter: "Rechter Außenrand",
    topInner: "Oberer Innenrand",
    topOuter: "Oberer Außenrand",
    bottomInner: "Unterer Innenrand",
    bottomOuter: "Unterer Außenrand",
    disclaimerTitle: "⚠️ Haftungsausschluss",
    disclaimerParagraphs: [
      "⚠️ Dies ist eine inoffizielle Hobby-Anwendung.",
      "🎓 Sie soll eine erste Einschätzung der Karten-Zentrierung ermöglichen.",
      "❌ Die angezeigten Ergebnisse sind nicht offiziell und nicht garantiert.",
      "🧪 Nutzen Sie das Tool zur Vorabprüfung, aber verlassen Sie sich auf professionelle Bewertung."
    ]
  },
  es: {
    title: "Herramienta de Centración",
    subtitle: "Analiza la centración de tu carta Pokémon con precisión.",
    uploadInstruction: "Sube una imagen en alta resolución de tu carta.",
    dragGuides: "Arrastra los cuadros de colores para colocar las guías de borde.",
    resultTitle: "Resultados",
    globalCentering: "Centrado Global",
    horizontal: "Horizontal",
    vertical: "Vertical",
    mm: "mm",
    percent: "%",
    psa: "Nota PSA",
    bgs: "Nota BGS",
    sgc: "Nota SGC",
    instructionsTab: "📘 Instrucciones",
    toolTab: "🛠️ Herramienta",
    languageLabel: "Idioma",
    uploadButton: "Subir Imagen",
    resetButton: "Reiniciar",
    generatePdfButton: "Generar PDF",
    downloadButton: "Descargar PDF",
    leftInner: "Borde interno izquierdo",
    leftOuter: "Borde externo izquierdo",
    rightInner: "Borde interno derecho",
    rightOuter: "Borde externo derecho",
    topInner: "Borde superior interno",
    topOuter: "Borde superior externo",
    bottomInner: "Borde inferior interno",
    bottomOuter: "Borde inferior externo",
    disclaimerTitle: "⚠️ Descargo de responsabilidad",
    disclaimerParagraphs: [
      "⚠️ Esta es una aplicación no oficial de aficionados.",
      "🎓 Su propósito es dar una idea preliminar del centrado de una carta.",
      "❌ Los resultados y calificaciones no son oficiales ni garantizados.",
      "🧪 Úsala como herramienta previa, pero confía en una evaluación profesional para el grading."
    ]
  },
  pt: {
    title: "Ferramenta de Centralização",
    subtitle: "Analise a centralização do seu cartão Pokémon com precisão.",
    uploadInstruction: "Envie uma imagem de alta resolução do seu cartão.",
    dragGuides: "Arraste os quadrados coloridos para posicionar os guias de borda.",
    resultTitle: "Resultados",
    globalCentering: "Centralização Global",
    horizontal: "Horizontal",
    vertical: "Vertical",
    mm: "mm",
    percent: "%",
    psa: "Nota PSA",
    bgs: "Nota BGS",
    sgc: "Nota SGC",
    instructionsTab: "📘 Instruções",
    toolTab: "🛠️ Ferramenta",
    languageLabel: "Idioma",
    uploadButton: "Carregar Imagem",
    resetButton: "Redefinir",
    generatePdfButton: "Gerar PDF",
    downloadButton: "Baixar PDF",
    leftInner: "Borda interna esquerda",
    leftOuter: "Borda externa esquerda",
    rightInner: "Borda interna direita",
    rightOuter: "Borda externa direita",
    topInner: "Borda superior interna",
    topOuter: "Borda superior externa",
    bottomInner: "Borda inferior interna",
    bottomOuter: "Borda inferior externa",
    disclaimerTitle: "⚠️ Aviso Legal",
    disclaimerParagraphs: [
      "⚠️ Este é um aplicativo amador não oficial.",
      "🎓 Ele serve para dar uma ideia inicial da centralização do cartão.",
      "❌ Os resultados e notas não são oficiais nem garantidos.",
      "🧪 Use como pré-análise, mas conte com uma avaliação profissional para o grading."
    ]
  }
};

export default translations;
