const translations = {
  it: {
    title: "Strumento di Centratura",
    subtitle: "Analizza la centratura della tua carta Pokémon con precisione.",
    uploadInstruction: "Carica un'immagine ad alta risoluzione della tua carta.",
    dragGuides: "Trascina i quadratini colorati per posizionare le guide ai bordi.",
    resultTitle: "Risultati",
    globalCentering: "Centratura Globale",
    horizontal: "Orizzontale",
    vertical: "Verticale",
    mm: "mm",
    percent: "%",
    psa: "Voto PSA",
    bgs: "Voto BGS",
    sgc: "Voto SGC",
    instructionsTab: "📘 Istruzioni",
    toolTab: "🛠️ Strumento",
    languageLabel: "Lingua",
    uploadButton: "Carica Immagine",
    resetButton: "Reset",
    downloadButton: "Scarica PDF",
    leftInner: "Bordo sinistro interno",
    leftOuter: "Bordo sinistro esterno",
    rightInner: "Bordo destro interno",
    rightOuter: "Bordo destro esterno",
    topInner: "Bordo superiore interno",
    topOuter: "Bordo superiore esterno",
    bottomInner: "Bordo inferiore interno",
    bottomOuter: "Bordo inferiore esterno",
    disclaimerTitle: "⚠️ Disclaimer",
    disclaimerParagraphs: [
      "⚠️ Questa è un'applicazione amatoriale.",
      "🎓 È pensata per fornire un'idea preliminare della centratura di una carta.",
      "❌ I risultati e i voti ipotetici non sono ufficiali né garantiscono il voto reale.",
      "🧪 Usala come pre-analisi, ma affidati a una valutazione professionale per il grading."
    ]
  },
  en: {
    title: "Centering Tool",
    subtitle: "Analyze your Pokémon card centering with precision.",
    uploadInstruction: "Upload a high-resolution image of your card.",
    dragGuides: "Drag the colored squares to place border guides.",
    resultTitle: "Results",
    globalCentering: "Global Centering",
    horizontal: "Horizontal",
    vertical: "Vertical",
    mm: "mm",
    percent: "%",
    psa: "PSA Grade",
    bgs: "BGS Grade",
    sgc: "SGC Grade",
    instructionsTab: "📘 Instructions",
    toolTab: "🛠️ Tool",
    languageLabel: "Language",
    uploadButton: "Upload Image",
    resetButton: "Reset",
    downloadButton: "Download PDF",
    leftInner: "Left Inner Border",
    leftOuter: "Left Outer Border",
    rightInner: "Right Inner Border",
    rightOuter: "Right Outer Border",
    topInner: "Top Inner Border",
    topOuter: "Top Outer Border",
    bottomInner: "Bottom Inner Border",
    bottomOuter: "Bottom Outer Border",
    disclaimerTitle: "⚠️ Disclaimer",
    disclaimerParagraphs: [
      "⚠️ This is a non-official hobby application.",
      "🎓 It is intended to provide a preliminary idea of card centering.",
      "❌ Results and grades shown are not official and not guaranteed.",
      "🧪 Use it as a pre-analysis tool, but rely on professional grading for certification."
    ]
  },
  fr: {
    title: "Outil de Centrage",
    subtitle: "Analysez le centrage de votre carte Pokémon avec précision.",
    uploadInstruction: "Téléchargez une image haute résolution de votre carte.",
    dragGuides: "Faites glisser les carrés colorés pour placer les repères de bord.",
    resultTitle: "Résultats",
    globalCentering: "Centrage Global",
    horizontal: "Horizontal",
    vertical: "Vertical",
    mm: "mm",
    percent: "%",
    psa: "Note PSA",
    bgs: "Note BGS",
    sgc: "Note SGC",
    instructionsTab: "📘 Instructions",
    toolTab: "🛠️ Outil",
    languageLabel: "Langue",
    uploadButton: "Télécharger Image",
    resetButton: "Réinitialiser",
    downloadButton: "Télécharger PDF",
    leftInner: "Bord intérieur gauche",
    leftOuter: "Bord extérieur gauche",
    rightInner: "Bord intérieur droit",
    rightOuter: "Bord extérieur droit",
    topInner: "Bord supérieur intérieur",
    topOuter: "Bord supérieur extérieur",
    bottomInner: "Bord inférieur intérieur",
    bottomOuter: "Bord inférieur extérieur",
    disclaimerTitle: "⚠️ Avertissement",
    disclaimerParagraphs: [
      "⚠️ Ceci est une application amateur.",
      "🎓 Elle est destinée à fournir une idée préliminaire du centrage d'une carte.",
      "❌ Les résultats et notes ne sont pas officiels ni garantis.",
      "🧪 Utilisez-la comme outil préliminaire, mais faites appel à un service de notation professionnel."
    ]
  },
  de: {
    title: "Zentrierungs-Tool",
    subtitle: "Analysieren Sie die Zentrierung Ihrer Pokémon-Karte präzise.",
    uploadInstruction: "Laden Sie ein hochauflösendes Bild Ihrer Karte hoch.",
    dragGuides: "Ziehen Sie die farbigen Quadrate, um Randführungen zu platzieren.",
    resultTitle: "Ergebnisse",
    globalCentering: "Globale Zentrierung",
    horizontal: "Horizontal",
    vertical: "Vertikal",
    mm: "mm",
    percent: "%",
    psa: "PSA Bewertung",
    bgs: "BGS Bewertung",
    sgc: "SGC Bewertung",
    instructionsTab: "📘 Anleitung",
    toolTab: "🛠️ Werkzeug",
    languageLabel: "Sprache",
    uploadButton: "Bild Hochladen",
    resetButton: "Zurücksetzen",
    downloadButton: "PDF Herunterladen",
    leftInner: "Linker Innenrand",
    leftOuter: "Linker Außenrand",
    rightInner: "Rechter Innenrand",
    rightOuter: "Rechter Außenrand",
    topInner: "Oberer Innenrand",
    topOuter: "Oberer Außenrand",
    bottomInner: "Unterer Innenrand",
    bottomOuter: "Unterer Außenrand",
    disclaimerTitle: "⚠️ Haftungsausschluss",
    disclaimerParagraphs: [
      "⚠️ Dies ist eine inoffizielle Hobby-Anwendung.",
      "🎓 Sie soll eine erste Einschätzung der Karten-Zentrierung ermöglichen.",
      "❌ Die angezeigten Ergebnisse sind nicht offiziell und nicht garantiert.",
      "🧪 Nutzen Sie das Tool zur Vorabprüfung, aber verlassen Sie sich auf professionelle Bewertung."
    ]
  },
  es: {
    title: "Herramienta de Centración",
    subtitle: "Analiza la centración de tu carta Pokémon con precisión.",
    uploadInstruction: "Sube una imagen en alta resolución de tu carta.",
    dragGuides: "Arrastra los cuadros de colores para colocar las guías de borde.",
    resultTitle: "Resultados",
    globalCentering: "Centrado Global",
    horizontal: "Horizontal",
    vertical: "Vertical",
    mm: "mm",
    percent: "%",
    psa: "Nota PSA",
    bgs: "Nota BGS",
    sgc: "Nota SGC",
    instructionsTab: "📘 Instrucciones",
    toolTab: "🛠️ Herramienta",
    languageLabel: "Idioma",
    uploadButton: "Subir Imagen",
    resetButton: "Reiniciar",
    downloadButton: "Descargar PDF",
    leftInner: "Borde interno izquierdo",
    leftOuter: "Borde externo izquierdo",
    rightInner: "Borde interno derecho",
    rightOuter: "Borde externo derecho",
    topInner: "Borde superior interno",
    topOuter: "Borde superior externo",
    bottomInner: "Borde inferior interno",
    bottomOuter: "Borde inferior externo",
    disclaimerTitle: "⚠️ Descargo de responsabilidad",
    disclaimerParagraphs: [
      "⚠️ Esta es una aplicación no oficial de aficionados.",
      "🎓 Su propósito es dar una idea preliminar del centrado de una carta.",
      "❌ Los resultados y calificaciones no son oficiales ni garantizados.",
      "🧪 Úsala como herramienta previa, pero confía en una evaluación profesional para el grading."
    ]
  },
  pt: {
    title: "Ferramenta de Centralização",
    subtitle: "Analise a centralização do seu cartão Pokémon com precisão.",
    uploadInstruction: "Envie uma imagem de alta resolução do seu cartão.",
    dragGuides: "Arraste os quadrados coloridos para posicionar os guias de borda.",
    resultTitle: "Resultados",
    globalCentering: "Centralização Global",
    horizontal: "Horizontal",
    vertical: "Vertical",
    mm: "mm",
    percent: "%",
    psa: "Nota PSA",
    bgs: "Nota BGS",
    sgc: "Nota SGC",
    instructionsTab: "📘 Instruções",
    toolTab: "🛠️ Ferramenta",
    languageLabel: "Idioma",
    uploadButton: "Carregar Imagem",
    resetButton: "Redefinir",
    downloadButton: "Baixar PDF",
    leftInner: "Borda interna esquerda",
    leftOuter: "Borda externa esquerda",
    rightInner: "Borda interna direita",
    rightOuter: "Borda externa direita",
    topInner: "Borda superior interna",
    topOuter: "Borda superior externa",
    bottomInner: "Borda inferior interna",
    bottomOuter: "Borda inferior externa",
    disclaimerTitle: "⚠️ Aviso Legal",
    disclaimerParagraphs: [
      "⚠️ Este é um aplicativo amador não oficial.",
      "🎓 Ele serve para dar uma ideia inicial da centralização do cartão.",
      "❌ Os resultados e notas não são oficiais nem garantidos.",
      "🧪 Use como pré-análise, mas conte com uma avaliação profissional para o grading."
    ]
  },
  zh: {
    title: "居中工具",
    subtitle: "精准分析您的宝可梦卡片居中情况。",
    uploadInstruction: "上传您的卡片高分辨率图像。",
    dragGuides: "拖动彩色方块以放置边缘参考线。",
    resultTitle: "结果",
    globalCentering: "整体居中",
    horizontal: "水平",
    vertical: "垂直",
    mm: "毫米",
    percent: "%",
    psa: "PSA 评分",
    bgs: "BGS 评分",
    sgc: "SGC 评分",
    instructionsTab: "📘 使用说明",
    toolTab: "🛠️ 工具",
    languageLabel: "语言",
    uploadButton: "上传图片",
    resetButton: "重置",
    downloadButton: "下载 PDF",
    leftInner: "左内边",
    leftOuter: "左外边",
    rightInner: "右内边",
    rightOuter: "右外边",
    topInner: "上内边",
    topOuter: "上外边",
    bottomInner: "下内边",
    bottomOuter: "下外边",
    disclaimerTitle: "⚠️ 免责声明",
    disclaimerParagraphs: [
      "⚠️ 本应用为非官方的业余工具。",
      "🎓 仅用于初步评估卡片的居中情况。",
      "❌ 显示的结果和评分不具有官方效力，也无法保证。",
      "🧪 请作为预分析参考，正式评分应依赖专业机构。"
    ]
  },
  ko: {
    title: "중심 정렬 도구",
    subtitle: "포켓몬 카드의 중심 정렬을 정밀하게 분석하세요.",
    uploadInstruction: "카드의 고해상도 이미지를 업로드하세요.",
    dragGuides: "색상 사각형을 드래그하여 테두리 가이드를 배치하세요.",
    resultTitle: "결과",
    globalCentering: "전체 중심 정렬",
    horizontal: "수평",
    vertical: "수직",
    mm: "mm",
    percent: "%",
    psa: "PSA 점수",
    bgs: "BGS 점수",
    sgc: "SGC 점수",
    instructionsTab: "📘 설명서",
    toolTab: "🛠️ 도구",
    languageLabel: "언어",
    uploadButton: "이미지 업로드",
    resetButton: "초기화",
    downloadButton: "PDF 다운로드",
    leftInner: "왼쪽 내부 테두리",
    leftOuter: "왼쪽 외부 테두리",
    rightInner: "오른쪽 내부 테두리",
    rightOuter: "오른쪽 외부 테두리",
    topInner: "상단 내부 테두리",
    topOuter: "상단 외부 테두리",
    bottomInner: "하단 내부 테두리",
    bottomOuter: "하단 외부 테두리",
    disclaimerTitle: "⚠️ 면책 조항",
    disclaimerParagraphs: [
      "⚠️ 이 앱은 비공식적인 취미용 도구입니다.",
      "🎓 카드 중심 정렬을 미리 파악하기 위한 용도로 제공됩니다.",
      "❌ 표시된 결과와 등급은 공식적인 것이 아니며 보장되지 않습니다.",
      "🧪 정식 평가를 위해서는 전문가의 그레이딩을 이용하세요."
    ]
  },
  ja: {
    title: "センタリングツール",
    subtitle: "ポケモンカードのセンタリングを正確に分析します。",
    uploadInstruction: "カードの高解像度画像をアップロードしてください。",
    dragGuides: "色付きの四角をドラッグしてガイドを配置します。",
    resultTitle: "結果",
    globalCentering: "全体のセンタリング",
    horizontal: "水平",
    vertical: "垂直",
    mm: "mm",
    percent: "%",
    psa: "PSA評価",
    bgs: "BGS評価",
    sgc: "SGC評価",
    instructionsTab: "📘 使い方",
    toolTab: "🛠️ ツール",
    languageLabel: "言語",
    uploadButton: "画像をアップロード",
    resetButton: "リセット",
    downloadButton: "PDFをダウンロード",
    leftInner: "左内側の枠",
    leftOuter: "左外側の枠",
    rightInner: "右内側の枠",
    rightOuter: "右外側の枠",
    topInner: "上内側の枠",
    topOuter: "上外側の枠",
    bottomInner: "下内側の枠",
    bottomOuter: "下外側の枠",
    disclaimerTitle: "⚠️ 免責事項",
    disclaimerParagraphs: [
      "⚠️ このアプリは非公式の趣味ツールです。",
      "🎓 カードのセンタリングを事前に確認するためのものです。",
      "❌ 表示された結果や評価は公式なものではなく、保証されません。",
      "🧪 正式な評価には専門のグレーディングサービスを利用してください。"
    ]
  },
};

export default translations;
